---
title: "Map"
author: "Yuehan Xiao"
date: "3/24/2018"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggmap)
library(tidyverse)
library(magick)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
gc <- c(-4.543678,50.82664)
map_water <- get_map(gc, source="stamen", maptype = "watercolor",zoom=14)
map_road <- get_map(gc, source="google", maptype = "roadmap",zoom=14)
lon <- c(-4.553962,-4.551349,-4.552814,-4.543023)
lat <- c(50.83587,50.83054,50.83347,50.83007)
df <- data.frame("lon" = lon, "lat" = lat)
```

## Water Map with 4 locations

```{r, echo=FALSE, warning=FALSE}
ggmap(map_water) +
  geom_point(
    aes(x = df$lon, y = df$lat),
    data = df, color = "red", size = 3
  )
```

## Road Map with 4 locations and shortest distance 

```{r, echo=FALSE, message= FALSE, warning=FALSE}
from <- "Bude North Cornwall Cricket Club, Bude, UK"
to <- "The Barrel at Bude"
route_df <- route(from, to, mode="walking", structure = "route")
ggmap(map_road) +
  geom_path(
    aes(x = lon, y = lat), color = "red", size = 2,
    data = route_df, lineend = "round")+
  geom_point(aes(x=df$lon, y=df$lat),
             data=df, color = "red", size=2)
```



##Picture for Crooklets Beach

```{r, echo=FALSE, warning=FALSE,fig.height=8,fig.width=8}
CrookletsBeach<-image_scale(image_read('https://www.cornwall-beaches.co.uk/public/photos/crooklets.jpg',"600x"))%>%
  image_annotate("Crooklet Beach", size = 20, color = "white")
plot(CrookletsBeach)
```



##Picture for Summerleaze Beach

```{r, echo=FALSE, warning=FALSE,fig.height=8,fig.width=8}
SummerleazeBeach<-image_scale(image_read('https://www.aspects-holidays.co.uk/webpics/CMS/Owners/Bude.jpg',"600x"))%>%
  image_annotate("Summerleaze Beach", size = 20, color = "white")
plot(SummerleazeBeach)
```



##Picture for Bude North Cornwall Cricket Club

```{r, echo=FALSE, warning=FALSE,fig.height=8,fig.width=8}
Cricket<-image_scale(image_read('https://www.telegraph.co.uk/content/dam/Travel/galleries/travel/destinations/europe/uk/Englands-most-beautiful-cricket-grounds/cricket-bude_3378037a.jpg',"x300"))%>%
  image_annotate("Cricket Club", size = 20, color = "white")
plot(Cricket)
```



##Picture for The Barrel at Bude

```{r, echo=FALSE, warning=FALSE,fig.height=8,fig.width=8}
Barrel<-image_scale(image_read('http://www.micropubassociation.co.uk/wp-content/uploads/barrel-800x800.jpg',"x300"))%>%
  image_annotate("The Barrel at Bude", size = 20, color = "white")
plot(Barrel)
```

